using System.ComponentModel.DataAnnotations;

namespace CampusServicePortal.DTOs.Events;

public class VenueDto { public int VenueId { get; set; } public string Name { get; set; } = string.Empty; public string VenueType { get; set; } = string.Empty; public int Capacity { get; set; } public string? Location { get; set; } public bool IsActive { get; set; } }
public class SaveVenueDto { [Required, MaxLength(150)] public string Name { get; set; } = string.Empty; [Required, RegularExpression("^(Event Hall|Open Space)$")] public string VenueType { get; set; } = string.Empty; [Range(1, 100000)] public int Capacity { get; set; } [MaxLength(150)] public string? Location { get; set; } public bool IsActive { get; set; } = true; }
public class SaveEventDto { [Required, MaxLength(200)] public string Title { get; set; } = string.Empty; [MaxLength(2000)] public string? Description { get; set; } [Required] public int VenueId { get; set; } public DateTime StartsAt { get; set; } public DateTime EndsAt { get; set; } [Range(1, 100000)] public int Capacity { get; set; } public bool UsesReservedSeating { get; set; } public bool IsActive { get; set; } = true; }
public class EventDto { public int EventId { get; set; } public string Title { get; set; } = string.Empty; public string? Description { get; set; } public int VenueId { get; set; } public string VenueName { get; set; } = string.Empty; public string VenueType { get; set; } = string.Empty; public int VenueCapacity { get; set; } public DateTime StartsAt { get; set; } public DateTime EndsAt { get; set; } public int Capacity { get; set; } public int RegisteredCount { get; set; } public int AvailableSlots { get; set; } public bool UsesReservedSeating { get; set; } public bool IsRegistrationOpen { get; set; } public bool IsActive { get; set; } }
public class EventSeatDto { public int EventSeatId { get; set; } public string SeatNumber { get; set; } = string.Empty; public bool IsAvailable { get; set; } }
public class CreateEventSeatDto { [Required, MaxLength(50)] public string SeatNumber { get; set; } = string.Empty; }
public class CreateEventRegistrationDto { [Required] public int EventId { get; set; } public int? EventSeatId { get; set; } }
public class EventRegistrationDto { public int EventRegistrationId { get; set; } public int UserId { get; set; } public int EventId { get; set; } public string EventTitle { get; set; } = string.Empty; public string VenueName { get; set; } = string.Empty; public DateTime StartsAt { get; set; } public DateTime EndsAt { get; set; } public string? SeatNumber { get; set; } public string Status { get; set; } = string.Empty; public DateTime RegisteredAt { get; set; } }
